# Generated by Django 2.2.5 on 2020-03-27 09:11

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CommonValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=500)),
                ('memory', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('Health', models.CharField(blank=True, max_length=50, null=True, verbose_name='Health & Fitness Features')),
                ('water_resistance', models.CharField(max_length=50)),
                ('communication', models.CharField(max_length=50)),
                ('wireless', models.CharField(blank=True, max_length=50, null=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='phone')),
                ('description', models.CharField(max_length=500)),
                ('memory', models.CharField(max_length=50)),
                ('connectivity', models.CharField(blank=True, max_length=50, null=True)),
                ('camera', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('hearing', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hearing Aid Compatibility')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('display', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.CommonValue')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('dual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dual', to='main_app.CommonValue')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='os', to='main_app.CommonValue')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone')),
                ('cat', models.ForeignKey(blank=True, default='4', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='commonvalue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Status'),
        ),
        migrations.AddField(
            model_name='commonvalue',
            name='val',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Value'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Phone')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.Status'),
        ),
    ]
