# Generated by Django 2.2.5 on 2020-04-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
