# Generated by Django 2.2.5 on 2020-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_phone_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
