# Generated by Django 2.2.5 on 2020-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='shipping',
            field=models.CharField(max_length=50),
        ),
    ]
