# Generated by Django 2.2.5 on 2020-04-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_phone_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Status'),
        ),
    ]
