# Generated by Django 2.2.5 on 2020-04-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200417_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='dimensions',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
